### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by niekvanderlaan**
Several bugfixes implemented, including but not limited to time addition, player image rendering and player lives updating. <bug>

### CODE REVIEW

**Comment by dvantetering** [comment]
Nice! Thanks for fixing it :)

**Comment by tieswesterborg** [comment]
No merge conflicts! Looks gooed <review>

**Comment by nubcaker** [comment]
Great work, much fix, such wow. omg.

**Comment by niekvanderlaan** [comment]
Thanks guys I tried! <review

**Comment by dvantetering** [comment]
And got so far.. <review

**Comment by niekvanderlaan** [comment]
But in the end <review>

**Comment by dvantetering** [comment]
it does really matter!!!!  <comment

**Pull request merged**
